#!/bin/sh
sudo ip route del 10.66.171.0/24 dev wlan0
sudo ip route add 10.66.171.0/24 dev eth0
sleep 5
sudo route add default gw 10.66.171.10 eth0

echo "setting up ethernet for internet access... warning turning off wifi!"
